spring:
  jpa:
    hibernate:
      ddl-auto: update # update the schema if necessary

jwt:
  expiration-minutes: 1000

nginx:
  required-proxy: false

chrip:
  rate-limit:
    ip:
      apply-limit: false