spring:
  jpa:
    hibernate:
      ddl-auto: validate
  mail:
    host: smtp.mailgun.org
    username: 어@sandbox54f44f7b0b7642fc90132576cf127953.mailgun.org

jwt:
  expiration-minutes: 15

nginx:
  required-proxy: true

chrip:
  email:
    url: "https://"
  rate-limit:
    ip:
      apply-limit: true